spring.application.name=order-service

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/orders}


#spring.data.mongodb.uri=mongodb://admin:adminpassword@mongo:27017/orders?authSource=admin

